group-id: com.palantir.haruspex
products:
  prometheus:
    build:
      main-pkg: ./cmd/prometheus
      output-dir: sls/prometheus/build
      os-archs:
        - os: linux
          arch: amd64
    dist:
      input-dir: sls/prometheus/files
      output-dir: sls/prometheus/dist
      dist-type:
        type: sls
        info:
          reloadable: true
          service-args: --config.file=$CONFIG_FILE --storage.tsdb.path=$STORAGE_TSDB_PATH --web.listen-address=$WEB_LISTEN_ADDRESS --web.enable-https=$WEB_ENABLE_HTTPS --web.certificate-file=$WEB_CERTIFICATE_FILE --web.key-file=$WEB_KEY_FILE --web.basic-username=$WEB_BASIC_USERNAME --web.basic-password=$WEB_BASIC_PASSWORD --web.external-url=$WEB_EXTERNAL_URL --web.route-prefix=$WEB_ROUTE_PREFIX --log.level=$LOG_LEVEL --web.enable-lifecycle
          manifest-extensions:
            no-stop: true
            restart-cron: true
            product-dependencies: []
            upgrade-strategy: rolling
            quorum-requirement: any
    docker:
    - repository: srx/prometheus/prometheus
      tag: snapshot
      context-dir: ./sls/prometheus
      info:
        type: sls
        data:
          group-id: com.palantir.haruspex
          manifest-extensions:
            no-stop: true
            restart-cron: true
            product-dependencies: []
            upgrade-strategy: rolling
            quorum-requirement: any
            volumes:
              data:
                desired-size: 100G
