tasks-config-providers:
  resolvers:
  - https://publish.artifactory.palantir.build/artifactory/internal-dist-release/{{GroupPath}}/{{Product}}/{{Version}}/{{Product}}-{{Version}}.yml
  providers:
  - locator:
      id: com.palantir.di-godel-config:di-godel-config:1.7.0
plugins:
  resolvers:
  - https://artifactory.palantir.build/artifactory/internal-dist/{{GroupPath}}/{{Product}}/{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
  - locator:
      id: com.palantir.deployability:godel-mockery-plugin:0.1.0
exclude:
  names:
  - \..+
  - vendor
  paths:
  - godel
  - fireengine-api
  - mocks
